{% set version = "4.4.1.1" %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 7f040a0542ed3f6d27f3002b074e509614e18d6c515b2005d1537fec01b24909
  patches:
    - dfile.c.patch  # [win]
    - dim.c.patch  # [win]
    - semantics.c.patch  # [win]
    - dap.path  # [win]
    - CMakeLists.patch  # [win]

build:
  number: 7
  skip: True  # [win and py36]
  features:
    - vc{{ vc }}  # [win]
  run_exports:
    # C has good backcompat, C++ has poor.  Since we don't make distinction, go with poor
    #   https://abi-laboratory.pro/tracker/timeline/netcdf/
    #   https://abi-laboratory.pro/tracker/timeline/netcdf-cxx/
    - {{ pin_subpackage('libnetcdf', max_pin='x.x.x') }}

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - {{ compiler('c') }}
    # not sure if we need cxx compiler here - seems to be presently disabled.
    # - {{ compiler('cxx') }}
    # not sure if we need fortran compiler here - seems to be presently disabled.
    # - {{ compiler('fortran') }}
  host:
    - msinttypes  # [win and vc<14]
    - curl
    - zlib
    - hdf4
    - hdf5
  run:
    - curl
    # zlib removed here because zlib package has run_exports for itself
    #    https://github.com/AnacondaRecipes/zlib-feedstock/pull/2
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    # - zlib 1.2.8
    # hdf4 removed here because package has run_exports for itself
    #     https://github.com/AnacondaRecipes/hdf4-feedstock/pull/1
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    #  - hdf4
    # hdf5 removed here because hdf5 package has run_exports for itself
    #    https://github.com/AnacondaRecipes/hdf5-feedstock/pull/1/files#diff-e178b687b10a71a3348107ae3154e44cR31
    # this req isn't actually necessary, as run_exports will add it.  Left here for reference.
    # - hdf5
    # - hdf5 1.8.18|1.8.18.*

test:
  commands:
    - nc-config --all  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf.so  # [linux]
    - test -f ${PREFIX}/lib/libnetcdf.dylib  # [osx]
    - ncdump -h http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic
    - ncdump -h https://data.nodc.noaa.gov/thredds/dodsC/ioos/sccoos/scripps_pier/scripps_pier-2016.nc
    - conda inspect linkages -p $PREFIX libnetcdf  # [not win]
    - conda inspect objects -p $PREFIX libnetcdf  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: 'Libraries and data formats that support array-oriented scientific data.'

extra:
  recipe-maintainers:
    - groutr
    - ocefpaf
    - kmuehlbauer
    - msarahan
