{% set version = "4.6.1" %}

package:
  name: libnetcdf
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: a2fabf27c72a5ee746e3843e1debbaad37cd035767eaede2045371322211eebb
  patches:
    - CMakeLists.patch  # [win]

build:
  number: 3
  run_exports:
    # C has good backcompat, C++ has poor.  Since we only build C, go with good
    #   https://abi-laboratory.pro/tracker/timeline/netcdf/
    #   https://abi-laboratory.pro/tracker/timeline/netcdf-cxx/
    - {{ pin_subpackage('libnetcdf') }}

requirements:
  build:
    - cmake
    - pkg-config  # [not win]
    - msinttypes  # [win and vc<14]
    - curl
    - zlib
    - hdf4
    - hdf5
    - {{ compiler('c') }}
    # not sure if we need cxx compiler here - seems to be presently disabled.
    # - {{ compiler('cxx') }}
    # not sure if we need fortran compiler here - seems to be presently disabled.
    # - {{ compiler('fortran') }}
  run:
    - curl

test:
  commands:
    - test -f ${PREFIX}/lib/libnetcdf.a  # [not win]
    - test -f ${PREFIX}/lib/libnetcdf.so  # [linux]
    - test -f ${PREFIX}/lib/libnetcdf.dylib  # [osx]
    - ncdump -h "http://geoport-dev.whoi.edu/thredds/dodsC/estofs/atlantic"
    - ncdump -h "https://data.nodc.noaa.gov/thredds/dodsC/ioos/sccoos/scripps_pier/scripps_pier-2016.nc"
    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/hioos/model/atm/ncep_pac/NCEP_Pacific_Atmospheric_Model_best.ncd"
    - ncdump -h "http://oos.soest.hawaii.edu/thredds/dodsC/usgs_dem_10m_tinian"
    - ncdump -h "https://www.ncei.noaa.gov/thredds/dodsC/namanl/201609/20160929/namanl_218_20160929_1800_006.grb"
    - nc-config --all  # [not win]
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.unidata.ucar.edu/software/netcdf/
  license: MIT
  license_file: COPYRIGHT
  summary: 'Libraries and data formats that support array-oriented scientific data.'

extra:
  recipe-maintainers:
    - groutr
    - ocefpaf
    - kmuehlbauer
    - msarahan
