{% set name = "libnetcdf" %}
{% set version = "4.9.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Unidata/netcdf-c/archive/v{{ version }}.tar.gz
  sha256: 990f46d49525d6ab5dc4249f8684c6deeaf54de6fec63a187e9fb382cc0ffdff
  patches:
    - patches/0004-Prefer-getenv-TOPSRCDIR-over-STRINGIFY-TOPSRCDIR.patch
    - patches/0009-topsrcdir.patch
    - patches/fix-s3-support.patch

build:
  number: 0
  run_exports:
    # C has good backcompat, C++ has poor.  Since we only build C, go with good
    #   https://abi-laboratory.pro/tracker/timeline/netcdf/
    #   https://abi-laboratory.pro/tracker/timeline/netcdf-cxx/
    - {{ pin_subpackage('libnetcdf') }}
  ignore_run_exports:
    - bzip2
    - jpeg
    - zlib
  missing_dso_whitelist: # [osx]
    - '*/libnetcdf.19.dylib'  # [osx]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pkg-config  # [not win]
    - gnuconfig   # [unix]
    - unzip     # [not win]
    - m2-unzip  # [win]
    - m4  # [not win]
    - m2-m4  # [win]
    - wget  # [not win]
    - diffutils  # [linux]
  host:
    - blosc {{ blosc }}
    - bzip2 {{ bzip2 }}
    - hdf4 {{ hdf4 }}
    - hdf5 {{ hdf5 }}
    - libaec {{ libaec }}
    - libcurl {{ libcurl }}
    - libxml2 {{ libxml2 }}
    - libzip 1.8.0
    # Openssl provides libcrypto which is needed via libcurl, but doesn't get
    # to the run reqs through run_exports because it is twice removed
    - openssl {{ openssl }}  # [not win]
    - zlib {{ zlib }}
    - zstd {{ zstd }}
  run:
    - libcurl
    - hdf4
    - hdf5
    - libzip
    - openssl  # [not win]
    - zlib

about:
  home: https://github.com/Unidata/netcdf-c
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYRIGHT
  summary: Libraries and data formats that support array-oriented scientific data.
  description: |
    The Unidata network Common Data Form (netCDF) is an interface for scientific data access
    and a freely-distributed software library that provides an implementation of the interface.
    The netCDF library also defines a machine-independent format for representing scientific data.
    Together, the interface, library, and format support the creation, access, and sharing of
    scientific data. The current netCDF software provides C interfaces for applications and data.
    Separate software distributions available from Unidata provide Java, Fortran, Python, and C++
    interfaces. They have been tested on various common platforms.
  dev_url: https://github.com/Unidata/netcdf-c
  doc_url: https://docs.unidata.ucar.edu/netcdf-c/current

extra:
  recipe-maintainers:
    - groutr
    - kmuehlbauer
    - ocefpaf
    - mingwandroid
    - msarahan
